user 1000 1000;   # задаём пользователя для worker-процессов

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # Подключаем все конфиги сайтов из /etc/nginx/conf.d/
    include /etc/nginx/conf.d/*.conf;
}
